project:
  title: project_title
  authors: []
  description : ''
  version: '1.0.0'
  sources: ['src']
  assets: ['assets']
  defines: []
  shaders: []
  libraries: []

input:
  mouse: true
  keyboard: true
  gamepad: true
  touch: true
  pen: false

app:
  name: app_name
  package: com.package.name
  icon: ''
  
html5:
  webgl: true
  canvas: 'kanvas'
  script: 'game'
  width: 800
  height: 600
  serverPort: 8080
  htmlFile: ''
  favicon: ''
  minify: false

windows:
  graphics: 'direct3d11'
  
compiler:
  output: 'build'
  parameters: ['-dce full']
  options: ['']
  haxe: ''
  kha: ''
  ffmpeg: ''
